### ISSUE TITLE
Support multiple tokens at issuance

### ISSUE THREAD

**Issue by dvorak42** [alxdavids/draft-privacy-pass#1]
(Adding an issue, can try drafting up a PR shortly)

It should be possible for a client to get multiple tokens issued at one time to avoid having to do a round-trip for each invocation of the issuance. The issuer might also want to publish the maximum number of tokens they'll issue at once (so the client knows how many blinded tokens to generate and send).

**Comment by alxdavids** [comment]
Yes this should be included, we should highlight that we can use the Batch_ functionality of the VOPRF to do this. Happy to accept a PR if you're still planning on writing one up.

**Comment by dvorak42** [comment]
I'll try getting one out in the next week or so after IETF things.
